<?php

namespace AppBundle\Repository;

/**
 * ArtworkUserEmotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArtworkUserEmotionRepository extends \Doctrine\ORM\EntityRepository
{
}
