<?php

namespace AppBundle\Repository;

/**
 * EmotionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EmotionRepository extends \Doctrine\ORM\EntityRepository
{
}
